### ISSUE TITLE
TimeoutError: The read operation timed out

### ISSUE THREAD

**Issue by aklira** [wojtkow/TeslaMonitor#1]
Hi,
I keep getting this error:
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.tesla.com', port=443): Read timed out. (read timeout=10)

Any idea on what could be the cause of this error ?

When I try the same url with the browser, everything works fine.

**Comment by cosygarcia** [comment]
Hi,

I have a similar problem.

python3 teslamonitor.py
https://www.tesla.com/inventory/api/v1/inventory-results?query=%7B%22query%22%3A%20%7B%22model%22%3A%20%22my%22%2C%20%22condition%22%3A%20%22new%22%2C%20%22arrangeby%22%3A%20%22Price%22%2C%20%22order%22%3A%20%22asc%22%2C%20%22market%22%3A%20%22PL%22%2C%20%22language%22%3A%20%22pl%22%2C%20%22super_region%22%3A%20%22europe%22%2C%20%22zip%22%3A%20%2200050%22%2C%20%22range%22%3A%200%7D%2C%20%22offset%22%3A%200%2C%20%22count%22%3A%2050%2C%20%22outsideOffset%22%3A%200%2C%20%22outsideSearch%22%3A%20false%7D
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib64/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/lib64/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.tesla.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.tesla.com', port=443): Max retries exceeded with url: /inventory/api/v1/inventory-results?query=%7B%22query%22%3A%20%7B%22model%22%3A%20%22my%22%2C%20%22condition%22%3A%20%22new%22%2C%20%22arrangeby%22%3A%20%22Price%22%2C%20%22order%22%3A%20%22asc%22%2C%20%22market%22%3A%20%22PL%22%2C%20%22language%22%3A%20%22pl%22%2C%20%22super_region%22%3A%20%22europe%22%2C%20%22zip%22%3A%20%2200050%22%2C%20%22range%22%3A%200%7D%2C%20%22offset%22%3A%200%2C%20%22count%22%3A%2050%2C%20%22outsideOffset%22%3A%200%2C%20%22outsideSearch%22%3A%20false%7D (Caused by ReadTimeoutError("HTTPSConnectionPool(host='www.tesla.com', port=443): Read timed out. (read timeout=10)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/teslamonitor.py", line 119, in <module>
    teslaRequest = s.get(url, timeout=10, allow_redirects = True, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.tesla.com', port=443): Max retries exceeded with url: /inventory/api/v1/inventory-results?query=%7B%22query%22%3A%20%7B%22model%22%3A%20%22my%22%2C%20%22condition%22%3A%20%22new%22%2C%20%22arrangeby%22%3A%20%22Price%22%2C%20%22order%22%3A%20%22asc%22%2C%20%22market%22%3A%20%22PL%22%2C%20%22language%22%3A%20%22pl%22%2C%20%22super_region%22%3A%20%22europe%22%2C%20%22zip%22%3A%20%2200050%22%2C%20%22range%22%3A%200%7D%2C%20%22offset%22%3A%200%2C%20%22count%22%3A%2050%2C%20%22outsideOffset%22%3A%200%2C%20%22outsideSearch%22%3A%20false%7D (Caused by ReadTimeoutError("HTTPSConnectionPool(host='www.tesla.com', port=443): Read timed out. (read timeout=10)"))

**Comment by wojtkow** [comment]
Unfortunately Tesla has added additional checks to their API and, at the moment, I'm not able to find a way to bypass that checks in teslamonitor.py.
However I've added teslamonitorselenium.py script, that uses selenium framework. This framework uses real browser (chrome in the cases of this script) and is much harder to block. Unfortunately it is limited to computers / servers with installed chrome / chromium and access to graphical console.
I close that issue, but I will still try to bypass current limitation in standard script.
